In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics
import pickle
from sklearn.preprocessing import  LabelEncoder

D:\Anaconda\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
def evauation_model(pred, y_val):
  return metrics.accuracy_score(pred, y_val)

In [3]:
def models_score(train_data, y_train, val_data, y_val):
    reg = SVC()
    reg.fit(train_data, y_train)
    pred = reg.predict(val_data)
    return metrics.accuracy_score(pred, y_val)

In [4]:
data = pd.read_csv(r"D:\Python\ArtyvisTechnologies\heart.csv")
categorical_features = ['ChestPainType', 'ST_Slope']
numeric_features = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
eda_df = data.loc[:, numeric_features]
eda_df.columns

Index(['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak'], dtype='object')

In [5]:
def one_hot_encode(df, column_dict):
  for column, prefix in column_dict.items():
    dummies = pd.get_dummies(df[column], prefix = prefix)
    df = pd.concat([df, dummies], axis = 1)
    df = df.drop(column, axis = 1)
  return df

In [6]:
# data = one_hot_encode(data, dict(zip(categorical_features, ['CP', 'ST'])))

In [7]:
# data["Sex"] = data.groupby("Sex").ngroup()
# data["RestingECG"] = data.groupby("RestingECG").ngroup()
# data["ExerciseAngina"] = data.groupby("ExerciseAngina").ngroup()

In [8]:
rs = RobustScaler()
label_encoder = LabelEncoder()

X = data.drop('HeartDisease', axis = 1)
y = data['HeartDisease']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [10]:
X_train['Sex'] = label_encoder.fit_transform(X_train['Sex'].values)
X_test['Sex'] = label_encoder.transform(X_test['Sex'].values)

X_train['ChestPainType'] = label_encoder.fit_transform(X_train['ChestPainType'].values)
X_test['ChestPainType'] = label_encoder.transform(X_test['ChestPainType'].values)

X_train['FastingBS'] = label_encoder.fit_transform(X_train['FastingBS'].values)
X_test['FastingBS'] = label_encoder.transform(X_test['FastingBS'].values)

X_train['RestingECG'] = label_encoder.fit_transform(X_train['RestingECG'].values)
X_test['RestingECG'] = label_encoder.transform(X_test['RestingECG'].values)

X_train['ExerciseAngina'] = label_encoder.fit_transform(X_train['ExerciseAngina'].values)
X_test['ExerciseAngina'] = label_encoder.transform(X_test['ExerciseAngina'].values)

X_train['ST_Slope'] = label_encoder.fit_transform(X_train['ST_Slope'].values)
X_test['ST_Slope'] = label_encoder.transform(X_test['ST_Slope'].values)

In [11]:
X_train_scaled = pd.DataFrame(rs.fit_transform(X_train), columns = X_train.columns)
X_test_scaled = pd.DataFrame(rs.transform(X_test), columns = X_test.columns)

In [12]:
pickle.dump(rs, open('rs.pkl', 'wb'))

In [13]:
score = models_score(X_train_scaled, y_train, X_test_scaled, y_test)

In [14]:
svm_model = SVC()
svm_model.fit(X_train_scaled,y_train)
pred = svm_model.predict(X_test_scaled)

In [15]:
score1 = evauation_model(pred,y_test)

In [16]:
svcHeart = 'svcHeart.sav'
pickle.dump(svm_model, open(svcHeart, 'wb'))

In [17]:
score1

0.8659420289855072

In [18]:
svm_model.predict([[40,1,1,140,289,0,1,172,0,0,2]])


D:\Anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


array([1], dtype=int64)

In [22]:
svm_model.predict([[-2.76923077,0.,1.,-0.5,-0.63185379,0.,0.,-0.55944056,0.,-0.33333333,0.]])

D:\Anaconda\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  "X does not have valid feature names, but"


array([1], dtype=int64)

In [20]:
pred

array([1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0], dtype=int64)

In [24]:
X_test.head(6)

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
900   58    1              0        114          318          0           2   
570   56    1              0        128          223          0           2   
791   51    1              0        140          298          0           1   
189   53    1              0        180          285          0           2   
372   63    1              0        185            0          0           1   
191   50    1              1        170          209          0           2   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  
900    140               0      4.4         0  
570    119               1      2.0         0  
791    122               1      4.2         1  
189    120               1      1.5         1  
372     98               1      0.0         2  
191    116               0      0.0         2